[build]
  environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" }
  publish = "out"
  command = "yarn run build-prod"

[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"  
  NEXT_PUBLIC_CONTRACT_ID = "REPLACE_WITH_CONTRACT_ADDRESS"  
  NEXT_PUBLIC_NETWORK_ID = "REPLACE_WITH_NETWORK_ID"  
  NEXT_PUBLIC_NETWORK_NAME = "REPLACE_WITH_NETWORK_NAME"  
  NEXT_PUBLIC_PINATA_API_KEY = "REPLACE_WITH_PINATA_API_KEY"  
  NEXT_PUBLIC_PINATA_API_SECRET = "REPLACE_WITH_PINATA_API_SECRET"  
