name: dummy

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always
    ENVIRONMENT: development
    GH_TOKEN: ${{ github.token }}

jobs:
    job1:
        uses: prosopo/captcha/.github/workflows/check_version.yml@v1
    check:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            # Checkout the repo
            - uses: actions/checkout@v3

            - name: abc
              run: |
                  echo ${{ needs.job1.outputs.bump }}
                  echo ${{ needs.job1.outputs.current_version }}
                  echo ${{ needs.job1.outputs.next_version }}
                  echo hello
